# Last two digits of port number are the MAJOR.MINOR of the data source
# Everything ahead of the last two digits are standard for the given service
#
# Network name is cbb-{service name}-{service MAJOR.MINOR}
version: '2'
services:
  mongo30:
    image: mongo
    container_name: crypto_mongo30
    networks:
      - cbb_mongo30
    ports:
      - "27030:27017"
  redis:
    image: redis:3.2-alpine
    container_name: crypto_redis32
    networks:
      - cbb_redis32
    ports:
      - "6332:6379"
networks:
  cbb_mongo30:
    external:
      name: cbb_mongo30
  cbb_redis32:
    external:
      name: cbb_redis32
